### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Gobot1234** [Gobot1234/steam-ext-csgo#1]
- [x] Set up protobufs and base framework.
- [x] SO messages. These need testing.
- [x] Examples, README and setup.py.
- [x] Matches.
